Repository techcsispit/mini-projs, pull requests merged in 2023-10, with the labels that each got.

#7 Calculator, Encryption/Decryption, PasswordStrength
  Calculator/index.html
  Calculator/use.js
  EncrypterDecrypterApp/index.html
  EncrypterDecrypterApp/scripts.js
  EncrypterDecrypterApp/styles.css
  PasswordStrengthChecker/index.html
  PasswordStrengthChecker/script.js
  PasswordStrengthChecker/style.css
Labels: enhancement, bugfix

#14 Blobmaker Deprecation Fix
  Blobmaker/app.js
  Blobmaker/index.html
Labels: bugfix

#18 Issue #16: improved overall ui/ux
  .DS_Store
  MovieInfoApp/.DS_Store
  MovieInfoApp/assets/.DS_Store
  MovieInfoApp/assets/images/.DS_Store
  MovieInfoApp/assets/images/background.png
  MovieInfoApp/index.css
  MovieInfoApp/index.html
  MovieInfoApp/index.js
Labels: enhancement

#17 Adding a new project in Java
  Calculator/index.html
  Movie_Ticket_Reservation_Simulator/Booked.txt
  Movie_Ticket_Reservation_Simulator/FileMethods.java
  Movie_Ticket_Reservation_Simulator/Green_tick.png
  Movie_Ticket_Reservation_Simulator/PVRLogo1.png
  Movie_Ticket_Reservation_Simulator/READ_ME_FIRST.txt
  Movie_Ticket_Reservation_Simulator/Reservation.java
  Movie_Ticket_Reservation_Simulator/RunCode.java
  Movie_Ticket_Reservation_Simulator/Ticket_Record.txt
  Movie_Ticket_Reservation_Simulator/emailtemp.txt
  Movie_Ticket_Reservation_Simulator/seat3.png
  Movie_Ticket_Reservation_Simulator/seats_temp.txt
  Movie_Ticket_Reservation_Simulator/sseat.png
  Movie_Ticket_Reservation_Simulator/taken_seat.png
Labels: enhancement

#11 Update BinaryVisualiser script.js
  BinaryVisualiser/assets/css/style.css
  BinaryVisualiser/assets/js/script.js
  BinaryVisualiser/index.html
Labels: enhancement

#19 Issue #16: Enhanced the Voice Generator Application
  VoiceGenerator/.gitignore
  VoiceGenerator/index.html
  VoiceGenerator/script.js
  VoiceGenerator/style.css
Labels: enhancement
